pipeline {
  agent any
  tools{
    maven 'maven 3.6.1'
  }
  
  stages{
    stage("build"){
      steps{
        echo 'Compiling users app..'
        dir('java/cmad-ms-users'){
          sh 'mvn compile'
        }
      }
    }
    stage("test"){
      steps{
        echo 'Running Unit Tets on new user app'
        dir('java/cmad-ms-users'){
          sh 'mvn clean test'
        }
      }
    }
     stage("package"){
      steps{
        echo 'Packaging user app'
        dir('java/cmad-ms-users'){
          sh 'mvn  package -DskipTests'
        }
      }
    }
  }
  post{
    always{
      echo 'Building multibranch pipeline for users is complete'
    }
  }
}
